// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: match.proto

#include "match.pb.h"
#include "match.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* MatchService_method_names[] = {
  "/MatchService/GetRoomList",
  "/MatchService/CreateRoom",
  "/MatchService/EnterRoom",
  "/MatchService/LeaveRoom",
  "/MatchService/StartGame",
  "/MatchService/EnterUser",
  "/MatchService/LeaveUser",
  "/MatchService/CreateRoomTCP",
  "/MatchService/AddServer",
};

std::unique_ptr< MatchService::Stub> MatchService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MatchService::Stub> stub(new MatchService::Stub(channel, options));
  return stub;
}

MatchService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetRoomList_(MatchService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateRoom_(MatchService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_EnterRoom_(MatchService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_LeaveRoom_(MatchService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StartGame_(MatchService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_EnterUser_(MatchService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_LeaveUser_(MatchService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateRoomTCP_(MatchService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AddServer_(MatchService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MatchService::Stub::GetRoomList(::grpc::ClientContext* context, const ::User& request, ::RoomList* response) {
  return ::grpc::internal::BlockingUnaryCall< ::User, ::RoomList, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetRoomList_, context, request, response);
}

void MatchService::Stub::async::GetRoomList(::grpc::ClientContext* context, const ::User* request, ::RoomList* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::User, ::RoomList, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRoomList_, context, request, response, std::move(f));
}

void MatchService::Stub::async::GetRoomList(::grpc::ClientContext* context, const ::User* request, ::RoomList* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRoomList_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::RoomList>* MatchService::Stub::PrepareAsyncGetRoomListRaw(::grpc::ClientContext* context, const ::User& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::RoomList, ::User, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetRoomList_, context, request);
}

::grpc::ClientAsyncResponseReader< ::RoomList>* MatchService::Stub::AsyncGetRoomListRaw(::grpc::ClientContext* context, const ::User& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRoomListRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MatchService::Stub::CreateRoom(::grpc::ClientContext* context, const ::CreatedRoomInfo& request, ::Room* response) {
  return ::grpc::internal::BlockingUnaryCall< ::CreatedRoomInfo, ::Room, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateRoom_, context, request, response);
}

void MatchService::Stub::async::CreateRoom(::grpc::ClientContext* context, const ::CreatedRoomInfo* request, ::Room* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::CreatedRoomInfo, ::Room, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateRoom_, context, request, response, std::move(f));
}

void MatchService::Stub::async::CreateRoom(::grpc::ClientContext* context, const ::CreatedRoomInfo* request, ::Room* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateRoom_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Room>* MatchService::Stub::PrepareAsyncCreateRoomRaw(::grpc::ClientContext* context, const ::CreatedRoomInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Room, ::CreatedRoomInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateRoom_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Room>* MatchService::Stub::AsyncCreateRoomRaw(::grpc::ClientContext* context, const ::CreatedRoomInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateRoomRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MatchService::Stub::EnterRoom(::grpc::ClientContext* context, const ::EnteredRoomInfo& request, ::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::EnteredRoomInfo, ::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_EnterRoom_, context, request, response);
}

void MatchService::Stub::async::EnterRoom(::grpc::ClientContext* context, const ::EnteredRoomInfo* request, ::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::EnteredRoomInfo, ::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_EnterRoom_, context, request, response, std::move(f));
}

void MatchService::Stub::async::EnterRoom(::grpc::ClientContext* context, const ::EnteredRoomInfo* request, ::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_EnterRoom_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Empty>* MatchService::Stub::PrepareAsyncEnterRoomRaw(::grpc::ClientContext* context, const ::EnteredRoomInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Empty, ::EnteredRoomInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_EnterRoom_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Empty>* MatchService::Stub::AsyncEnterRoomRaw(::grpc::ClientContext* context, const ::EnteredRoomInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncEnterRoomRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MatchService::Stub::LeaveRoom(::grpc::ClientContext* context, const ::User& request, ::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::User, ::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_LeaveRoom_, context, request, response);
}

void MatchService::Stub::async::LeaveRoom(::grpc::ClientContext* context, const ::User* request, ::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::User, ::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LeaveRoom_, context, request, response, std::move(f));
}

void MatchService::Stub::async::LeaveRoom(::grpc::ClientContext* context, const ::User* request, ::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LeaveRoom_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Empty>* MatchService::Stub::PrepareAsyncLeaveRoomRaw(::grpc::ClientContext* context, const ::User& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Empty, ::User, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_LeaveRoom_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Empty>* MatchService::Stub::AsyncLeaveRoomRaw(::grpc::ClientContext* context, const ::User& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLeaveRoomRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MatchService::Stub::StartGame(::grpc::ClientContext* context, const ::User& request, ::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::User, ::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StartGame_, context, request, response);
}

void MatchService::Stub::async::StartGame(::grpc::ClientContext* context, const ::User* request, ::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::User, ::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartGame_, context, request, response, std::move(f));
}

void MatchService::Stub::async::StartGame(::grpc::ClientContext* context, const ::User* request, ::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartGame_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Empty>* MatchService::Stub::PrepareAsyncStartGameRaw(::grpc::ClientContext* context, const ::User& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Empty, ::User, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StartGame_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Empty>* MatchService::Stub::AsyncStartGameRaw(::grpc::ClientContext* context, const ::User& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStartGameRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MatchService::Stub::EnterUser(::grpc::ClientContext* context, const ::EnteredRoomInfo& request, ::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::EnteredRoomInfo, ::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_EnterUser_, context, request, response);
}

void MatchService::Stub::async::EnterUser(::grpc::ClientContext* context, const ::EnteredRoomInfo* request, ::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::EnteredRoomInfo, ::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_EnterUser_, context, request, response, std::move(f));
}

void MatchService::Stub::async::EnterUser(::grpc::ClientContext* context, const ::EnteredRoomInfo* request, ::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_EnterUser_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Empty>* MatchService::Stub::PrepareAsyncEnterUserRaw(::grpc::ClientContext* context, const ::EnteredRoomInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Empty, ::EnteredRoomInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_EnterUser_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Empty>* MatchService::Stub::AsyncEnterUserRaw(::grpc::ClientContext* context, const ::EnteredRoomInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncEnterUserRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MatchService::Stub::LeaveUser(::grpc::ClientContext* context, const ::User& request, ::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::User, ::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_LeaveUser_, context, request, response);
}

void MatchService::Stub::async::LeaveUser(::grpc::ClientContext* context, const ::User* request, ::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::User, ::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LeaveUser_, context, request, response, std::move(f));
}

void MatchService::Stub::async::LeaveUser(::grpc::ClientContext* context, const ::User* request, ::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LeaveUser_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Empty>* MatchService::Stub::PrepareAsyncLeaveUserRaw(::grpc::ClientContext* context, const ::User& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Empty, ::User, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_LeaveUser_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Empty>* MatchService::Stub::AsyncLeaveUserRaw(::grpc::ClientContext* context, const ::User& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLeaveUserRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MatchService::Stub::CreateRoomTCP(::grpc::ClientContext* context, const ::CreatedRoomInfo& request, ::Room* response) {
  return ::grpc::internal::BlockingUnaryCall< ::CreatedRoomInfo, ::Room, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateRoomTCP_, context, request, response);
}

void MatchService::Stub::async::CreateRoomTCP(::grpc::ClientContext* context, const ::CreatedRoomInfo* request, ::Room* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::CreatedRoomInfo, ::Room, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateRoomTCP_, context, request, response, std::move(f));
}

void MatchService::Stub::async::CreateRoomTCP(::grpc::ClientContext* context, const ::CreatedRoomInfo* request, ::Room* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateRoomTCP_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Room>* MatchService::Stub::PrepareAsyncCreateRoomTCPRaw(::grpc::ClientContext* context, const ::CreatedRoomInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Room, ::CreatedRoomInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateRoomTCP_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Room>* MatchService::Stub::AsyncCreateRoomTCPRaw(::grpc::ClientContext* context, const ::CreatedRoomInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateRoomTCPRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MatchService::Stub::AddServer(::grpc::ClientContext* context, const ::ServerInfo& request, ::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ServerInfo, ::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AddServer_, context, request, response);
}

void MatchService::Stub::async::AddServer(::grpc::ClientContext* context, const ::ServerInfo* request, ::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ServerInfo, ::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddServer_, context, request, response, std::move(f));
}

void MatchService::Stub::async::AddServer(::grpc::ClientContext* context, const ::ServerInfo* request, ::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddServer_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Empty>* MatchService::Stub::PrepareAsyncAddServerRaw(::grpc::ClientContext* context, const ::ServerInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Empty, ::ServerInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AddServer_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Empty>* MatchService::Stub::AsyncAddServerRaw(::grpc::ClientContext* context, const ::ServerInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddServerRaw(context, request, cq);
  result->StartCall();
  return result;
}

MatchService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MatchService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MatchService::Service, ::User, ::RoomList, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MatchService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::User* req,
             ::RoomList* resp) {
               return service->GetRoomList(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MatchService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MatchService::Service, ::CreatedRoomInfo, ::Room, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MatchService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::CreatedRoomInfo* req,
             ::Room* resp) {
               return service->CreateRoom(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MatchService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MatchService::Service, ::EnteredRoomInfo, ::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MatchService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::EnteredRoomInfo* req,
             ::Empty* resp) {
               return service->EnterRoom(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MatchService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MatchService::Service, ::User, ::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MatchService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::User* req,
             ::Empty* resp) {
               return service->LeaveRoom(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MatchService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MatchService::Service, ::User, ::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MatchService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::User* req,
             ::Empty* resp) {
               return service->StartGame(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MatchService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MatchService::Service, ::EnteredRoomInfo, ::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MatchService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::EnteredRoomInfo* req,
             ::Empty* resp) {
               return service->EnterUser(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MatchService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MatchService::Service, ::User, ::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MatchService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::User* req,
             ::Empty* resp) {
               return service->LeaveUser(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MatchService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MatchService::Service, ::CreatedRoomInfo, ::Room, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MatchService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::CreatedRoomInfo* req,
             ::Room* resp) {
               return service->CreateRoomTCP(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MatchService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MatchService::Service, ::ServerInfo, ::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MatchService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ServerInfo* req,
             ::Empty* resp) {
               return service->AddServer(ctx, req, resp);
             }, this)));
}

MatchService::Service::~Service() {
}

::grpc::Status MatchService::Service::GetRoomList(::grpc::ServerContext* context, const ::User* request, ::RoomList* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MatchService::Service::CreateRoom(::grpc::ServerContext* context, const ::CreatedRoomInfo* request, ::Room* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MatchService::Service::EnterRoom(::grpc::ServerContext* context, const ::EnteredRoomInfo* request, ::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MatchService::Service::LeaveRoom(::grpc::ServerContext* context, const ::User* request, ::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MatchService::Service::StartGame(::grpc::ServerContext* context, const ::User* request, ::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MatchService::Service::EnterUser(::grpc::ServerContext* context, const ::EnteredRoomInfo* request, ::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MatchService::Service::LeaveUser(::grpc::ServerContext* context, const ::User* request, ::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MatchService::Service::CreateRoomTCP(::grpc::ServerContext* context, const ::CreatedRoomInfo* request, ::Room* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MatchService::Service::AddServer(::grpc::ServerContext* context, const ::ServerInfo* request, ::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}
